### ISSUE TITLE
網頁風格

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/calendarNTNU#5]
我考完試後來加 CSS

**Comment by wildskyf** [comment]
ref:
- https://www.pinterest.com/pin/340936634261899877/
- https://dribbble.com/shots/1219982-Booking-Calendar-Month/attachments/163612

**Comment by wildskyf** [comment]
電腦版差不多完工，剩下 RWD。

**Comment by RexYuan** [comment]
:fireworks:
