### ISSUE TITLE
活動之資料詳細度

### ISSUE THREAD

**Issue by WilliamSnail** [communityNTNU/calendarNTNU#7]
應該需要增加提交活動時
可以的話能夠輸入「地點」或是「活動詳細內容」

**Comment by wildskyf** [comment]
@RexYuan  順便報一個的問題：
![2015-12-17 00-29-21](https://cloud.githubusercontent.com/assets/6042803/11846821/4d31d4c6-a455-11e5-988f-068067b7bb9a.png)

他打紅星代表必填，但我只有一天，又叫我跳過？？

**Comment by RexYuan** [comment]
@WilliamSnail 加了地點 活動詳細內容應該就是「描述」欄位
@wi1d5ky 已改
